// AUTO-GENERATED by scripts/fetch-feed-bg.mjs — do not edit by hand.
// Static require() map of bundled feed background images (Metro needs literals).
import type { ImageSourcePropType } from 'react-native';

export const FEED_BG: ImageSourcePropType[] = [
  require('../assets/feed-bg/bg-01.jpg'), // gen/nature
  require('../assets/feed-bg/bg-02.jpg'), // gen/nature
  require('../assets/feed-bg/bg-03.jpg'), // gen/nature
  require('../assets/feed-bg/bg-04.jpg'), // gen/nature
  require('../assets/feed-bg/bg-05.jpg'), // gen/nature
  require('../assets/feed-bg/bg-06.jpg'), // gen/nature
  require('../assets/feed-bg/bg-07.jpg'), // gen/nature
  require('../assets/feed-bg/bg-08.jpg'), // gen/nature
  require('../assets/feed-bg/bg-09.jpg'), // gen/atmos
  require('../assets/feed-bg/bg-10.jpg'), // gen/atmos
  require('../assets/feed-bg/bg-11.jpg'), // gen/atmos
  require('../assets/feed-bg/bg-12.jpg'), // gen/atmos
  require('../assets/feed-bg/bg-13.jpg'), // gen/atmos
  require('../assets/feed-bg/bg-14.jpg'), // gen/atmos
  require('../assets/feed-bg/bg-15.jpg'), // gen/atmos
  require('../assets/feed-bg/bg-16.jpg'), // gen/atmos
  require('../assets/feed-bg/bg-17.jpg'), // gen/refined
  require('../assets/feed-bg/bg-18.jpg'), // gen/refined
  require('../assets/feed-bg/bg-19.jpg'), // gen/refined
  require('../assets/feed-bg/bg-20.jpg'), // gen/refined
  require('../assets/feed-bg/bg-21.jpg'), // gen/refined
  require('../assets/feed-bg/bg-22.jpg'), // gen/refined
  require('../assets/feed-bg/bg-23.jpg'), // gen/refined
  require('../assets/feed-bg/bg-24.jpg'), // med/medical
  require('../assets/feed-bg/bg-25.jpg'), // med/medical
  require('../assets/feed-bg/bg-26.jpg'), // med/medical
  require('../assets/feed-bg/bg-27.jpg'), // med/medical
  require('../assets/feed-bg/bg-28.jpg'), // med/medical
  require('../assets/feed-bg/bg-29.jpg'), // med/medical
  require('../assets/feed-bg/bg-30.jpg'), // med/medical
  require('../assets/feed-bg/bg-31.jpg'), // med/medical
  require('../assets/feed-bg/bg-32.jpg'), // med/medical
  require('../assets/feed-bg/bg-33.jpg'), // med/medical
  require('../assets/feed-bg/bg-34.jpg'), // med/medical
  require('../assets/feed-bg/bg-35.jpg'), // med/medical
  require('../assets/feed-bg/bg-36.jpg'), // law/law
  require('../assets/feed-bg/bg-37.jpg'), // law/law
  require('../assets/feed-bg/bg-38.jpg'), // law/law
  require('../assets/feed-bg/bg-39.jpg'), // law/law
  require('../assets/feed-bg/bg-40.jpg'), // law/law
  require('../assets/feed-bg/bg-41.jpg'), // law/law
  require('../assets/feed-bg/bg-42.jpg'), // law/law
  require('../assets/feed-bg/bg-43.jpg'), // law/law
  require('../assets/feed-bg/bg-44.jpg'), // biz/business
  require('../assets/feed-bg/bg-45.jpg'), // biz/business
  require('../assets/feed-bg/bg-46.jpg'), // biz/business
  require('../assets/feed-bg/bg-47.jpg'), // biz/business
  require('../assets/feed-bg/bg-48.jpg'), // biz/business
  require('../assets/feed-bg/bg-49.jpg'), // biz/business
  require('../assets/feed-bg/bg-50.jpg'), // biz/business
  require('../assets/feed-bg/bg-51.jpg'), // biz/business
  require('../assets/feed-bg/bg-52.jpg'), // biz/business
  require('../assets/feed-bg/bg-53.jpg'), // biz/business
];

export const FEED_BG_TAGS: string[] = ['nature', 'nature', 'nature', 'nature', 'nature', 'nature', 'nature', 'nature', 'atmos', 'atmos', 'atmos', 'atmos', 'atmos', 'atmos', 'atmos', 'atmos', 'refined', 'refined', 'refined', 'refined', 'refined', 'refined', 'refined', 'medical', 'medical', 'medical', 'medical', 'medical', 'medical', 'medical', 'medical', 'medical', 'medical', 'medical', 'medical', 'law', 'law', 'law', 'law', 'law', 'law', 'law', 'law', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business'];
// Field each image belongs to ('gen' | 'med' | 'law' | 'biz'), same order as FEED_BG.
export const FEED_BG_FIELD: string[] = ['gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'gen', 'med', 'med', 'med', 'med', 'med', 'med', 'med', 'med', 'med', 'med', 'med', 'med', 'law', 'law', 'law', 'law', 'law', 'law', 'law', 'law', 'biz', 'biz', 'biz', 'biz', 'biz', 'biz', 'biz', 'biz', 'biz', 'biz'];
